#!/bin/bash
echo "Packing new docs"
npm run build
rsync --delete -az -v _site/ root@cdn.pegasusgateway.com:/var/www/cdn/docs/

ssh root@cdn.pegasusgateway.com chown -R www-data:www-data /var/www/cdn/
echo "All done :)"
exit
